import pandas as pd
df = pd.read_csv('train.csv')
df.drop('id',axis=1,inplace=True)
df.drop('bdate',axis=1,inplace=True)
df.drop('has_photo',axis=1,inplace=True)
df.drop('has_mobile',axis=1,inplace=True)
df.drop('followers_count',axis=1,inplace=True)
df.drop('graduation',axis=1,inplace=True)
df.drop('education_form',axis=1,inplace=True)
df.drop('relation',axis=1,inplace=True)
df.drop('life_main',axis=1,inplace=True)
df.drop('people_main',axis=1,inplace=True)
df.drop('city',axis=1,inplace=True)
df.drop('occupation_name',axis=1,inplace=True)
df.dropna(inplace=True)
print(df.info())